{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "quality-audit-service.serviceAccountName" . }}
  labels:
{{ include "quality-audit-service.labels" . | indent 4 }}
{{- end -}}
